name: 'thiago-scherrer/botform'
description: 'Github Action and terraform'
inputs:
  tfarg:
    description: 'terraform arg'
    required: true
    default: 'plan'
  tfdir:
    description: 'terraform workdir'
    required: true
    default: '.'
  tfversion:
    description: 'terraform version'
    required: true
    default: '1.0.1'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tfarg }}
    - ${{ inputs.tfdir }}
    - ${{ inputs.tfversion }}
