name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: test-case-1
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out
      uses: actions/checkout@v2
    -
      name: plan
      uses: thiago-scherrer/botform@0.0.11
      with:
        tfarg: 'plan'
        tfdir: 'test'
    -
      name: apply
      uses: thiago-scherrer/botform@0.0.11
      with:
        tfarg: 'apply -auto-approve'
        tfdir: 'test'
